<div id="content">

<h1>Privacy Policy</h1>
<div class="divider"></div>

<p class="gentext_12"><?php echo $communityName?> has established this Privacy Policy to inform you how we collect and use the personal information that you provide to us and to others in the course of using our Services and to allow you to make an informed decision about how you will use our Services. Our “Services” include any and all of our websites, including <?php echo $appRootUrl ?>, and those domains directly associated with any of them, the app, and all related services, applications, components, programs, software, listings, directories, tools, message boards, databases and information offered by <?php echo $communityName?> and made available and utilized through each of the foregoing or through the websites of our partners. References to “you” in this Agreement means you, your duly authorized representatives and any entity you may represent in connection with your use of the Services.</p>
<p class="gentext_12">By registering to use our Services or by continuing to use our Services, where registration is not required, you are consenting to the terms of this Privacy Policy and acknowledge that information you provide to us through the Services will be subject to our information practices disclosed herein. If you do not agree to be bound by this Privacy Policy, you should not use our Services.</p>
<p class="gentext_12">The <?php echo $communityName?> Privacy Policy addresses only our practices with respect to information we collect about you in the course of using our Services and does not apply to information about you that might be collected by a third party website or an offering linked to or otherwise accessible from our Services. Any information collected, obtained and/or used by any such third parties is subject to the privacy policies of those third parties. Finally, to the extent any of our Services are undertaken in conjunction with or as a co-branded service with a third party, then both our Privacy Policy and such third party’s privacy policy may apply.</p>
<strong>The Information About You That We Collect</strong>
<p class="gentext_12">When you use our Services, you may provide <?php echo $communityName?> with information, including personally identifiable information, both directly through your own input, and indirectly, through your use of and interaction with the Services. Based on the Services you use, the information we may have access to, obtain, retain and use may include:</p>
<ul class="gentext_12">
	<li>Registration-related information, such as your name, e-mail addresses, telephone and fax numbers, home or work addresses, birth date or gender, and similar information;</li>
	<li>Information made available by you in those publicly accessible areas our Services that allow you to post information or content;</li>
	<li>Information about the websites you visit while using any portion of our Services, and information about the person or persons to whom you direct the usage of our Services to the extent knowable to us;</li>
	<li>Information about the contents of your posts and <?php echo $communityName?>, your responses to and interaction with the websites you use while using any portion of our Services and the content related thereto;</li>
	<li>Information about your use of our Services, such as the frequency with which you use them, how you use and interact with them, when you visit them, and your responses to the offerings and advertisements made available to you through them, among other things;</li>
	<li>Information about the searches you perform through the Services’ search functionality (if any), including without limitation the queries you submit, the results received in response to such queries and how you use the results of those searches;</li>
	<li>Information about any interactions you might have with our customer service tools and personnel about your use of our Services;</li>
	<li>Other information that may be obtained based on your use of a particular Service or offering; and/or</li>
	<li>Information of a technical nature that may be gathered or received when you use the Services, including, without limitation, the following:</li>
	<ul>
		<li>The type of browser you are using when using our Services (e.g., Internet Explorer, Safari, etc…);</li>
		<li>Your means of connecting to the Internet (e.g., connection speed through broadband or narrowband access;</li>
		<li>Your operating system type, whether Windows XP, Mac OS, and CPU type (for example, Pentium);</li>
		<li>Your Internet protocol (IP) address and information about the version of any software comprising a portion of the Services that you use; and/or</li>
		<li>Any information that may be gathered regarding your geographic location and the domain name of your Internet service provider (ISP);</li>
	</ul>
</ul>
<p class="gentext_12">All of the foregoing information is collectively referred to hereinafter as Your <?php echo $communityName?> Information. We may also supplement Your <?php echo $communityName?> Information with additional information from other third parties in some cases. Additionally, those portions of the Services comprised of software, including without limitation, the <?php echo $communityName?> Applications, have been configured to communicate to us any information relating to computer errors arising from use of such software, without providing any notice to you of the delivery of such communications. Such communications may include the configuration settings applicable at the time of the error. We use this data to help us clarify and fix performance issues with and to improve the software and the Services.</p>
<strong>How <?php echo $communityName?> Uses the Information We Gather</strong>

<p class="gentext_12">Your <?php echo $communityName?> Information is used to:</p>
<ul class="gentext_12">
	<li>Operate and improve upon the Services, including all constituent parts of the Services such as the software, the websites and the various offerings, among other things;</li>
	<li>Provide to you advertisements and content which is personalized to you;</li>
	<li>Satisfy your requests for products, offerings, programs, and services;</li>
	<li>Respond to any inquiries, questions and/or comments you might have and to otherwise communicate with you;</li>
	<li>Research and analyze your use of the Services; and</li>
	<li>Present you with offers for other products, offerings, programs, features and/or services that may be of interest to you. We will not share Your <?php echo $communityName?> Information with third parties unless:</li>
	<li>Such information has been published by you in Public Forums (as defined below).</li>
	<li>You have given us your prior consent to disclose such information;</li>
	<li>Such information is needed to complete a transaction you have requested;</li>
	<li>We must disclose some or all of Your <?php echo $communityName?> Information to authorized officers of the court in order to comply with valid legal process or to act in other urgent situations (as further discussed below);</li>
	<li>Such information is needed by a company that works for us in providing you with our Services, in which case they will only get that portion of Your <?php echo $communityName?> Information they need to help us deliver our Services and they will only be allowed to use that portion of Your <?php echo $communityName?> Information when we request it and pursuant to our instructions; and</li>
	<li>Another party receives the information you provide through portions of our Services which may be “Co-Sponsored” with a third party. A “Co-Sponsored” page or service is one which has both our name, <?php echo $communityName?>, on it and another party’s or parties’ name, branding, logos, graphics on it in such a way that is clear that it is a Co-Sponsored Service. For instance, our partners may make some or all of the Services available on portions of their websites and such use of some or all of the Services on portions of their websites would be a Co-Sponsored Service. Any information you voluntarily provide on a “Co-Sponsored” page or through a “Co-Sponsored” service will be accessible, retained and used by either party and in accordance with this Privacy Policy and the third party privacy policy. Accordingly, please be sure you have read both the partner’s and <?php echo $communityName?>’ privacy policies before providing information to or on such Co-Sponsored service or webpage.</li>
	<li>We may use contractors and agents in order to help us operate and provide the Services. If any such contractors and agents have access to personally identifiable information, we require them to protect this information in a manner that is consistent with this Privacy Policy. Additionally, you should be aware that our own personnel may occasionally have access and be exposed to random information, some of which may be Your <?php echo $communityName?> Information, as it goes through the <?php echo $communityName?> servers. Our personnel are also obligated to comply with and to protect this information in conformity with our Privacy Policy.</li>
</ul>
<p class="gentext_12">We note above, but it is worth reiterating here, that Your <?php echo $communityName?> Information, including your online communications such as the content of <?php echo $communityName?>, as well as other information about you as a user of our Services, may be disclosed by us to those authorized officers of the court in response to valid legal process, including without limitation, a valid court order, search warrant or subpoena), as well as in other circumstances if we believe in good faith that there is an emergency that poses a threat to the safety of you or another person or that the Services are being used in the commission of a crime by your or another third party. Furthermore, we may disclose Your <?php echo $communityName?> Information to protect our own rights, Services and property or those of our affiliated providers, in addition to providing you with the Services you have requested.</p>
<p class="gentext_12">In the event that ownership of all or a portion of the Services currently provided by <?php echo $communityName?> were to change as a result of a merger, acquisition or transfer to another company, Your <?php echo $communityName?> Information may be transferred as well.</p>
<strong>Web Beacons and Cookies</strong>
<p class="gentext_12">In providing the Services to you, we may use web beacons and cookies or similar technologies in conjunction with Your <?php echo $communityName?> Information to personalize and improve your use of and experience with the Services, including, without limitation, to help authenticate you when logging on to and using the Services; to operate and improve the Service’s offerings; to present, measure and research the effectiveness of our Service’s offerings, advertisements, and communications to you, such as by determining which pages you visit, which ads you click on, communications you respond to, and functionality you use; to store and allow retrieval of your registration information and configuration preferences; and to customize the content and advertisements provided to you through the Services. In addition, the websites of our partners on which our Services appear and third party advertisers on our site might also use cookies or web beacons on their websites or downloaded through our Services to accomplish many similar goals in connection with the effectiveness of their advertising through our Services and in general. We do not have access to the cookies or web beacons employed by our partners or our advertisers through our Services and such cookies or web beacons are not governed by this Privacy Policy, but rather by the privacy policy of such partner or advertiser.</p>
<p class="gentext_12">Web beacons or clear GIFs are relatively small pieces of code placed on webpages that can be used for a number of purposes, including counting the users who visit that webpage, or to deliver a cookie to the browser of a user viewing that page. A cookie is a small text file transferred from <?php echo $communityName?> to your computer that records information about your preferences and use of the Services, as more fully described above. We may also use such cookies to help us identify your location by determining your IP address, or to allow us to recall certain Service settings that you have chosen previously. You can control cookies through your browser’s settings. However, if you reject all cookies, you may not be able to take advantage of most our Service offerings.</p>
<strong>Public Forums and Personal Profile</strong>
<p class="gentext_12">If you disclose information about yourself publicly through use of certain portions of our Services such as the posting of <?php echo $communityName?> or to message boards, chat rooms, blogs, groups, lists, directories, your Personal Profile (as defined below) or any other area reasonably understood to be a public forum (collectively, the “Public Forums”), other users of our Services may be able to access and use any such information you provide. Therefore, before you post any information you should carefully consider whether you want such information to be accessible by others. We urge you to carefully consider where you provide information within our Services, since you may not be able to delete the information you have provided in some Public Forms, including, for example, <?php echo $communityName?>, message boards, chat sessions, or other portions of our Services that may be maintained by third parties. Additionally, you should be aware that others may be able to record certain information even if not made available in a Public Forum, such as the content of a private Qwip or an instant message, or your IP address. The IP address is an integral part of the TCP/IP standard protocol of the Internet and can be extracted by any party to the communication session using certain software and/or hardware.</p>
<p class="gentext_12">The Personal Profile is the area on the <?php echo $communityName?> website or application that allows a user to create a personal profile for him- or herself by supplying certain information or importing such information from other websites not associated with <?php echo $communityName?>. During registration or any time thereafter through use of the Services, users are able to add details to the Personal Profile. In some cases, we may require that you provide a nickname and/or email address, which information may be displayed in the Personal Profile and which may also be used as an identifier in connection with your use of the Services. Further, your login name may be used by other users of the Services to locate you through the Services and to properly communicate with you through the Services. Generally, it will not be a requirement that you provide any other personally identifiable information about yourself in connection with your use of the Services. Any information you choose to provide in your Personal Profile will be deemed to have been disclosed by you in a Public Forum.</p>
<strong>Direct Marketing Offers</strong>
<p class="gentext_12">Both during the registration process for our Services, as well as at other times during your use of the Services, you may be asked if you would like to receive certain promotional offerings from us, as well as certain of our partners. If you consent to receive such offers, you consent to our and/or our partners’ use of Your <?php echo $communityName?> Information to contact you and communicate with you about such promotions, including your SMS, email, or other electronic communications methods (generally referred to hereinafter as “Direct Marketing”).</p>
<p class="gentext_12">For purposes of clarity, Direct Marketing does not mean communications made to you or information sent to you by <?php echo $communityName?> through any means, including without limitation any of the aforementioned means, pertaining to your registration for the Services, the features of the Services, including new, modified or discontinued features, or the fulfillment or completion of certain transactions you have requested or initiated through the services, such as a purchase or service order. In addition, our provision to you of advertising through the Services or the provision of advertising from our partners through the Services does not constitute Direct Marketing. In connection with the provision of such advertising from our partners, we may provide them with aggregate data about groups of users, or specific data about individual users, including you, provided that in either case, such information is not capable of personally identifying you, unless otherwise agreed by you.</p>
<strong>Your Username and Password</strong>
<p class="gentext_12">You are responsible for keeping your password for certain of the Services confidential and secret. Anyone given your password will have the ability to edit your Personal Profile at any time. As such and for other important security reasons, we urge you to keep your password secure and safe at all times if you are assigned or create one. By using our Services, you acknowledge that you and you alone are responsible for the security of your username and password if you are assigned or create one.</p>
<strong>We Are Committed to Security</strong>
<p class="gentext_12"><?php echo $communityName?> has established safeguards and maintains strict protocols to help prevent unauthorized access to or misuse of Your <?php echo $communityName?> Information. However, notwithstanding these safeguards and protocols, we cannot guarantee that your personally identifiable information will never be disclosed in a manner inconsistent with this Privacy Policy. As an example, a third party may act in an unauthorized manner, including by violating applicable law and/or our Terms of Use, End User License Agreement, Acceptable Use Policy and this Privacy Policy (collectively, our “Terms of Service”) in order to access the Services in a manner which would allow access to your personally identifiable information.</p>
<strong>General Internet Hazards</strong>
<p class="gentext_12">Any time you receive files over the Internet from third parties, regardless of the application used, whether <?php echo $communityName?>, email or other application, you may be subjecting yourself to receiving harmful files or files that are not compatible with your operating system. Prior to accepting any files from any Internet user, including those from an account that appears familiar to you, we highly recommend verifying that the person sending you such files is the person you believe he or she is. You should be extremely careful about accepting files from users you do not trust, from users you do not know, or from users whose identity you have not been able to confirm. You should also be aware that communications sent over the Internet are not secure unless they are encrypted. <?php echo $communityName?> does not encrypt your communications through the Services. Further, your communications made through <?php echo $communityName?> may be routed through different countries which may have different laws, rules, regulations and standards regarding activities on the Internet. As such, <?php echo $communityName?> cannot accept any responsibility for any unauthorized access to your communications made through the Services or any loss of data.</p>
<strong>European Union Members - International Transfer of Data</strong>
<p class="gentext_12">Our Services are international in scope. By using the Services you consent to Your <?php echo $communityName?> Information being sent and processed in other jurisdictions, including the United States and other jurisdictions outside the European Union and European Economic Area where there may be less stringent data protection laws.</p>
<strong>Children Under Age 13</strong>
<p class="gentext_12">Our Services are intended for a general audience, and children under the age of thirteen are not permitted to register with us to use the Services. We do not intentionally solicit or collect personal information from anyone under the age of 13 or knowingly allow anyone under the age of 13 to register for our Services. If it comes to <?php echo $communityName?>’ attention through reliable means that a user of our Services is under the age of 13 then <?php echo $communityName?> will delete such users account. If you believe that we might have any information from or about a child under age 13, please contact us at <?php echo $infoEmail ?></p>
<strong>Children Between the Ages of 13 and 18</strong>
<p class="gentext_12">We strongly recommend that minors between the ages of 13 and 18 ask their parents permission before sending information about themselves to anyone over the Internet or receiving any information from persons unknown to them.</p>
<strong>How You Can Contact Us</strong>
<p class="gentext_12">If you have any questions or concerns about the Qbix Privacy Policy or its implementation, you may contact us at this email address: <a href="mailto:<?php echo $privacyEmail ?>"><?php echo $privacyEmail ?></a></p>
<strong>Changes to this Privacy Policy and Additional Information</strong>
<p class="gentext_12">Qbix may update this Privacy Policy from time to time in its sole discretion. As such, you should review this Privacy Policy periodically. If we make significant/material changes to our information practices, we will provide you with appropriate online notice, such as notification on the Qbix website or to your email address you provided to us as part of Your Qbix Information at least 30 days prior to the effectiveness of such material change. We may provide you with other privacy-related information in connection with your use of certain offerings from the Services, as well as for special features and services not described in this Privacy Policy that may be introduced in the future. This Privacy Policy is subject to our Terms of Use and End User License Agreement with respect to governing law, venue, dispute resolution, limitation of damages and intellectual property ownership.</p>
<strong>Who We Are</strong>
<p class="gentext_12">We are <?php echo $organizationName ?>. Any references made in this Privacy Policy to “us”, “we”, “our” and/or “<?php echo $communityName ?>” shall be deemed to have been made to <?php echo $organizationName ?>.</p>


</div>